sudo: required
services:
  - mysql
dist: trusty
language: node_js
node_js:
  - "5.0.0"

before_install:
  - cp setup/mysql-passwords.sample setup/mysql-passwords
  - setup/mysql_create  
  
install:
  - npm install
  - npm run-script migrate

script:
  - npm test
