sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
  - mysql
dist: trusty
language: node_js
node_js:
  - "5.0.0"

before_install:
  - cp config/config.json.travis config/config.json

install:
  - npm install

before_script:
  - mysql -e "create database mmh_dev;" -u root
  - mysql -e "create database mmh_test;" -u root

script:
  - npm run-script migrate
  - npm test
