#!/bin/bash


debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password password $mysql_root_password"
debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password_again password $mysql_root_password"
apt-get -y install mysql-server
#mysql -u root -p$mysql_root_password --version

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sed -e "s/\${mysql_admin_password}/$mysql_admin_password/" \
    -e "s/\${mysql_mmh_password}/$mysql_mmh_password/" \
    -e "s/\${mysql_mmh_dev_password}/$mysql_mmh_dev_password/" \
    -e "s/\${mysql_mmh_tests_password}/$mysql_mmh_tests_password/" \
    -e "s/\${mysql_mmh_sandbox_password}/$mysql_mmh_sandbox_password/" \
$DIR/mysql_create | mysql -f -u root -p$mysql_root_password

sed -e "s/\${mysql_admin_password}/$mysql_admin_password/" \
    -e "s/\${mysql_mmh_password}/$mysql_mmh_password/" \
    -e "s/\${mysql_mmh_dev_password}/$mysql_mmh_dev_password/" \
    -e "s/\${mysql_mmh_test_password}/$mysql_mmh_test_password/" \
    -e "s/\${mysql_mmh_sandbox_password}/$mysql_mmh_sandbox_password/" \
config/config.json.example > config/config.json

